name: Deploy to Amazon EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start

      - name: Deploy to Server EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.EC2_REMOTE_USER }}

      - name: Runserver
        run: python3 manage.py runserver 0.0.0.0:8000

